<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<LangVersion>latest</LangVersion>
		<Configurations>Debug;Release;Test;Pack;DebugSGen</Configurations>
	</PropertyGroup>

	<ItemGroup>
	  <Compile Remove="EnumsTest.cs" />
	  <Compile Remove="Test.cs" />
	</ItemGroup>
	
	<ItemGroup>
		<PackageReference Include="CommunityToolkit.Mvvm" Version="8.2.2" />
		<PackageReference Include="FluentAssertions" Version="6.12.0" PrivateAssets="all" />
		<!--<PackageReference Include="Microsoft.CodeAnalysis.Common" Version="4.4.0" />
		<PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="4.4.0" />-->
		<PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.9.0" PrivateAssets="all" />
		<PackageReference Include="SourceCrafter.ViewModelGenerator" Version="1.24.70.57" />
		<PackageReference Include="xunit" Version="2.7.0" PrivateAssets="all" />
		<PackageReference Include="xunit.runner.visualstudio" Version="2.5.7" PrivateAssets="all">
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="coverlet.collector" Version="6.0.1">
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
			<PrivateAssets>all</PrivateAssets>
		</PackageReference>
		<PackageReference Include="Riok.Mapperly" Version="4.1.1" ExcludeAssets="runtime" PrivateAssets="all" />
	</ItemGroup>
	<ItemGroup>
	  <ProjectReference Include="..\SourceCrafter.Mappify\SourceCrafter.Mappify.csproj" OutputItemType="Analyzer" />
	</ItemGroup>

	<!--<PropertyGroup Condition=" $(Configuation) == 'Debug' Or $(Configuation) == 'DEBUG_SG' ">
		<EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
		<CompilerGeneratedFilesOutputPath>GeneratedFiles</CompilerGeneratedFilesOutputPath>
	</PropertyGroup>-->


</Project>
