<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>netstandard2.0</TargetFramework>
        <LangVersion>latest</LangVersion>
        <Nullable>enable</Nullable>
        <EnforceExtendedAnalyzerRules>true</EnforceExtendedAnalyzerRules>
        <IsRoslynComponent>true</IsRoslynComponent>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
			<Configurations>Debug;Release;Pack;DebugSGen</Configurations>
    </PropertyGroup>

    <ItemGroup>
      <Compile Remove="Assignment.cs" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.CodeAnalysis.Common" Version="4.14.0" />
        <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="4.14.0" />
        <PackageReference Include="System.Memory" Version="4.5.5" PrivateAssets="all" GeneratePathProperty="true" />
        <PackageReference Include="IndexRange" Version="1.0.3" PrivateAssets="all" GeneratePathProperty="true" />
			<PackageReference Include="System.Runtime.InteropServices" PrivateAssets="all" Version="4.3.0" />
    </ItemGroup>

</Project>
